PowerSAM_sims
=============

simulation study to learn more about the performance of PowerSAM 

I want to build a plot of N by power for all the different measures. 

Test of AUC <= .6 vs AUC > .6 when the true AUC = .65

S0 is baseline survival at prediction time (5 years)

 - $Y \sim N(0,1)$
 - Measures estimated at $t_{predict} = 5$ with marker cutpoint value $c = 0$ 

```{r, echo = FALSE, results='hide', message=FALSE}
library(ggplot2)
library(reshape)
#process some data

if(FALSE){
S0 = c(0.80, .85, 0.90, 0.91, 0.92, 0.93, 0.94, 0.95, .96, .97, .98)
N = seq(100, 2000, 100)
C = c(50, 70, 90)


#only will have to do this once, then comment out

#beta <- data.frame(matrix(nrow= length(S0*length(N)), ncol = 4))
AUC <- data.frame(matrix(nrow= length(S0*length(N)), ncol = 6))
#TPR <- data.frame(matrix(nrow= length(S0*length(N)), ncol = 4))
#FPR <- data.frame(matrix(nrow= length(S0*length(N)), ncol = 4))
#PPV <- data.frame(matrix(nrow= length(S0*length(N)), ncol = 4))
#NPV <- data.frame(matrix(nrow= length(S0*length(N)), ncol = 4))
#names(beta) == names(TPR) = names(FPR ) = names(PPV) = names(NPV) 
 names(AUC) <- c("c", "N", "S0","method",  "Measure", "Power")

index = 0
for(s0 in S0){
  for(n in N){
    for(c in C){

   #load in data, take what we want
   filename = paste("data/simout_cens_",c, "_S0_", s0, "_N_", n, "_AUC_NP.Rdata", sep = "")
   
   if(file.access(filename)==0){ 
         index = index + 1
         load(filename) 
         #beta[index,] <- c(n, s0, "beta", mean(tmp$beta$power))
      AUC[index,] <- c(c, n, s0, "NP", "AUC", mean(tmp$AUC$power))
      #TPR[index,] <- c(n, s0, "TPR(0)", mean(tmp$TPR$power))
      #FPR[index,] <- c(n, s0, "FPR(0)", mean(tmp$FPR$power))   
      #PPV[index,] <- c(n, s0, "PPV(0)", mean(tmp$PPV$power))  
      #NPV[index,] <- c(n, s0, "NPV(0)", mean(tmp$NPV$power))   
   print(paste("n:", n, "  s0", s0, "   c", c))
   }else print(paste(filename, "failed!!!!!!"))
    
      
  }  
}
}
simData <- rbind(AUC)
simData$N <- as.numeric(simData$N)
simData$S0 <- as.numeric(simData$S0)
simData$Power <- as.numeric(simData$Power)
save(simData, file = "data/AUCData_NP.Rdata")

load("data/AUCData_SP.Rdata")
allData <- simData 
load("data/AUCData_NP.Rdata")
allData <- rbind(allData, simData) 

simData <- allData
save(simData, file = "data/AUCData_All.Rdata")

}

###already did above, just load in data
load("data/AUCData_All.Rdata")


g <- ggplot(subset(simData, is.element(c, c(50, 70, 90))), aes(x=N, y= Power, group= factor(S0), color = S0))
output_plot <-   g + 
                 geom_smooth(size = 1.2, se=FALSE) + 
                 facet_grid(c~method)+
                # scale_color_gradient(low = "red") +
                 geom_hline(yintercept = .9, size = 1.1, linetype = 2) +
                 scale_color_continuous(name=expression("S(t=3 | Y=0)"), low = "red") + 
                 theme(strip.text = element_text(size = 14), 
                       axis.text  = element_text(size = 16), 
                       legend.text = element_text(size = 14), 
                       legend.title = element_text(size = 16))
        


```

```{r fig.width=9, fig.height=14, echo = FALSE, message=FALSE, warning=FALSE}

output_plot

```

